function [BW,maskedImage] = fn_segimg_replay_connect(X)
%segmentImage Segment image using auto-generated code from Image Segmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the Image Segmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 21-Aug-2024
%----------------------------------------------------


% Adjust data to span data range.
X = imadjust(X);

% Auto clustering
s = rng;
rng('default');
L = imsegkmeans(single(X),2,'NumAttempts',2);
rng(s);
BW = L == 2;

% Dilate mask with disk
radius = 4;
decomposition = 6;
se = strel('disk', radius, decomposition);
BW = imdilate(BW, se);

% Close mask with disk
radius = 4;
decomposition = 6;
se = strel('disk', radius, decomposition);
BW = imclose(BW, se);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

